### ISSUE TITLE
[Design Issue] MDBT Work for MMIS

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#4222]
1. The MDBT (Medicaid Detailed Budget Table) inclusion for MMIS will be designed to support/have a designation for capturing DDI - Design Development & Installation funding.
2. The [sample MDBT,](https://docs.google.com/spreadsheets/d/1y_25C-E9tBLhhiH-e0ZxkqSZBfY2oL_y/edit#gid=1171187501) will be visually translated and itemized to show where the DDI funding is coming from (outside of the Executive Summary → Program Budget table).
3. The MDBT can span multiple federal fiscal years:
     - CMS Officer can approve 1yr (current) + 2nd yr, if the state provides enough justification and if their budget cycle will allow that. 
4. The following sections will need to be modified in the current design:
     - **Proposed Budget (Akua to implement)**
     - **Executive Summary (Sherry to implement)**
     -    Builder + Export View

---

Archived Notes (09/27/2022):
- Update the MMIS MDBT Screens to mirror the MDBT file. Excel exports will be done as part of a future functions.
- MDBT - should this export with the APD export as part of the export or as a separate excel file? incrementally, is it that much harder to export as excel as it is to insert it into the APD export PDF? 

### This task is done when…

- [x] Feature Discovery Session is conducted with PM
- [x] any acceptance criteria (not process oriented, requirements of feature)
- [x] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 visual, content, and UX considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
Below is the MDBT Classification Flow for future reference
https://app.mural.co/t/ccs9461/m/cmsmural6360/1654556103128/909fca2ea53fa1c0c3a86c87ccc88859f1980839?sender=975cbc89-ba0b-4c4b-bc70-885a5a7f9bc6

**Comment by akuas** [comment]
@jeromeleecms Future Jerome, what sorts of changes do you expect for the Summary Budget? Do you want the breakdown of fed/state share to be more granular?

**Comment by akuas** [comment]
Retiring this epic because it is no longer needed. Content in this epic is reflected in the tickets.
