### ISSUE TITLE
[Design Issue] Design Milestones as a Table for the Export/Read Only Views

### ISSUE THREAD

**Issue by akuas** [Enterprise-CMCS/eAPD#4525]
We should display the milestones as tables, because it may make the scan and review process simpler. We could model the design after the current activity schedule summary.

This ticket will not affect the builder view though, we should consider rethinking the milestones section. In the MES Expansion research, users noted that they have 10s of milestones per activity, that they should in a table. With the current design, they would have to input that information manually and having lots of milestones will cause this page to expand  significantly.

### This task is done when…

- [ ] Milestones table is designed 
- [ ] New design is reflected in the ready only and export view page designs
- [ ] 508 visual, content, and UX considerations and/or recommendations are
      reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---
